### ISSUE TITLE
Lay the foundations of the project

### ISSUE THREAD

**Issue by glezseoane** [glezseoane/olivetty#1]
In order to start working, it is necessary to specifically establish the scope of this project and its earliest versions.

- [x] Document the desired final scope of the mature version.
- [x] Create a roadmap.
- [x] Decide the technologies to use in the project.
- [x] Document why the name of the project and other curiosities.

**Comment by glezseoane** [comment]
Hi,

We are going to start whit this.

———————————————————————————————————
Borja González Seoane’s development garage
garaje@glezseoane.es <mailto:garaje@glezseoane.es> (GPG EFFAB097)
Costa da Morte, Galicia, Spain
glezseoane.es <http://glezseoane.es/en>
———————————————————————————————————
